image: gitlab.tz.marvelsoft.net:4567/docker/release_container_gitlab/release-container-gitlab
 
stages:
  - build
  - test

before_script:
  - export CCACHE_DISABLE=1
  - export DISTCC_HOSTS=$(sed '/$CI_RUNNER_DESCRIPTION/d' ~/.distcc/hosts | tr '\n' ' ')

debug_build:
  stage: build
  script: 
   - mkdir build
   - cd build
   - meson ..
   - ninja -j 64 test

release_build:
  stage: build
  script:
    - mkdir build
    - cd build
    - meson --buildtype=release ..
    - ninja -j 64 test

